---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: myk8scluster4
  namespace: myk8scluster4
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.96.0.0/11
    serviceDomain: k8s.test
    services:
      cidrBlocks:
      - 100.64.0.0/13
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: KubeadmControlPlane
    name: myk8scluster4-control-plane
    namespace: myk8scluster4
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: VCDCluster
    name: myk8scluster4
    namespace: myk8scluster4
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: VCDCluster
metadata:
  name: myk8scluster4
  namespace: myk8scluster4
spec:
  site: https://bos1-vcloud-static-172-29.eng.vmware.com
  org: tenant1
  ovdc: tenant1_ovdc
  ovdcNetwork: tenant1_ovdc_nw
  userContext:
    username: clusteradminuser
    password: ca$hc0w
    refreshToken:
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: VCDMachineTemplate
metadata:
  name: myk8scluster4-control-plane
  namespace: myk8scluster4
spec:
  template:
    spec:
      catalog: cse
      template: ubuntu-2004-kube-v1.21.2+vmware.1-tkg.1-7832907791984498322
      computePolicy: 2core2gb
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  name: myk8scluster4-control-plane
  namespace: myk8scluster4
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        timeoutForControlPlane: 2m0s
        certSANs:
        - localhost
        - 127.0.0.1
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
      dns:
        imageRepository: projects.registry.vmware.com/tkg
        imageTag: v1.8.0_vmware.5
      etcd:
        local:
          imageRepository: projects.registry.vmware.com/tkg
          imageTag: v3.4.13_vmware.15
      imageRepository: projects.registry.vmware.com/tkg
      kubernetesVersion: v1.21.2+vmware.1
    initConfiguration:
      nodeRegistration:
        criSocket: unix:///run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: unix:///run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
      kind: VCDMachineTemplate
      name: myk8scluster4-control-plane
      namespace: myk8scluster4
  replicas: 1
  version: v1.21.2+vmware.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: VCDMachineTemplate
metadata:
  name: capi-md-0
  namespace: myk8scluster4
spec:
  template:
    spec:
      catalog: cse
      template: ubuntu-2004-kube-v1.21.2+vmware.1-tkg.1-7832907791984498322
      computePolicy: 2core2gb
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
  name: capi-md-0
  namespace: myk8scluster4
spec:
  template:
    spec:
      joinConfiguration:
        discovery:
          bootstrapToken:
            apiServerEndpoint: 10.150.166.101:6443
            token: 5zwuwr.i2qx6bxid1biox39
            caCertHashes: 
            - sha256:6add650c421c42cfe3e3f7996ab84c93f9968383d3531befb376e47e3deec761
        nodeRegistration:
          criSocket: unix:///run/containerd/containerd.sock
          kubeletExtraArgs:
            cloud-provider: external
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachineDeployment
metadata:
  name: capi-md-0
  namespace: myk8scluster4
spec:
  clusterName: myk8scluster4
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
          kind: KubeadmConfigTemplate
          name: capi-md-0
          namespace: myk8scluster4
      clusterName: myk8scluster4
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: VCDMachineTemplate
        name: capi-md-0
        namespace: myk8scluster4
      version: v1.21.2+vmware.1
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Machine
metadata:
  name: mstr-8it1
  namespace: myk8scluster4
  labels:
    cluster.x-k8s.io/control-plane: nil
spec:
  clusterName: myk8scluster4
  bootstrap:
    dataSecretName: mstr-8it1
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
      kind: KubeadmConfigTemplate
      name: mstr-8it1
      namespace: myk8scluster4
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: VCDMachine
    name: mstr-8it1
    namespace: myk8scluster4
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: VCDMachine
metadata:
  name: mstr-8it1
  namespace: myk8scluster4
spec:
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Machine
metadata:
  name: node-h1fz
  namespace: myk8scluster4
spec:
  clusterName: myk8scluster4
  bootstrap: 
    dataSecretName: node-h1fz
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
      kind: KubeadmConfigTemplate
      name: node-h1fz
      namespace: myk8scluster4
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: VCDMachine
    name: node-h1fz
    namespace: myk8scluster4
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: VCDMachine
metadata:
  name: node-h1fz
  namespace: myk8scluster4
spec:
---
